### PR TITLE
Update to 0.0.25

### PR DESCRIPTION
**Pull request by Xstoudi**

### CODE REVIEW

**Comment by Xstoudi** [comment]
Here we go @stellarhopper :)

**Comment by stellarhopper** [comment]
I've merged this, but my copr repo for updating the build was recently pulled as Discord, being non-free software, is against copr's terms of use.

@Xstoudi would you like to perhaps look into an alternative means to host a repo?

**Comment by hevanaa** [comment]
FYI I'm now using this: https://copr.fedorainfracloud.org/coprs/tcg/discord/

**Comment by Xstoudi** [comment]
Sorry to hear this. As I am a noob in this domain, I don't know any other host.
I'm gonna use https://github.com/RPM-Outpost/discord for now.

**Comment by seancallaway** [comment]
As a side-note, I am working on getting Discord stable into [RPMFusion](https://bugzilla.rpmfusion.org/show_bug.cgi?id=4441). Packaging a binary application to their standards is taking quite a while, but will hopefully be worth it. In the meantime, it's available as a signed RPM from [my repo](http://repo.calnet.us/).

It should be noted that I'm not building `canary` at this time, but can work with @stellarhopper to get it into my build pipeline, I'd think.

**Pull request merged**
